### ISSUE TITLE
Кампʼютарная тэрміналогія

### ISSUE THREAD

**Issue by ssvb** [mikalai-udodau/spell-be#6]
У слоўніку не хапае шмат словаў з кампʼютарнай тэрміналогіі: байт, юнікод, плагін ды іншыя. Большасць з іх запазычаны з ангельскай мовы і магчыма адсутнічаюць у слоўніках літаратурнай мовы тыповых мастацкіх твораў. Ці мае сэнс гэтую праблему неяк вырашыць?

**Comment by mikalai-udodau** [comment]
Байт, гігабайт і тэрабайт трэба дадаваць, першыя два ўжо ёсць у папяровых слоўніках, а тэрабайт, калі з'явіцца, з вялікай доляй пэўнасці будзе выглядаць іменна так. Што нельга сказаць пра "унікод" - я схіляюся да думкі, што яго трэба пісаць з першай літарай у, але сустракаюцца варыянты. Што да "плагіна" - нават не ведаю, ці трэба яго ўключаць у слоўнік. На жаль, не прыжыўся ні адзін з варыянтаў перакладу, для такога ж "адона" - хібка-зыбка, але ж прыжыўся "дадатак".

**Comment by ssvb** [comment]
> "унікод" - я схіляюся да думкі, што яго трэба пісаць з першай літарай у, але сустракаюцца варыянты

Афіцыйная вікіпедыя выкарыстоўвае літару "у": https://be.wikipedia.org/wiki/%D0%A3%D0%BD%D1%96%D0%BA%D0%BE%D0%B4
Тарашкевіца выкарыстоўвае літару 'ю': https://be-tarask.wikipedia.org/wiki/%D0%AE%D0%BD%D1%96%D0%BA%D0%BE%D0%B4
GrammarDB ніводнага варыянта не мае.

> Што да "плагіна" - нават не ведаю, ці трэба яго ўключаць у слоўнік. На жаль, не прыжыўся ні адзін з варыянтаў перакладу, для такога ж "адона" - хібка-зыбка, але ж прыжыўся "дадатак".

У англійскай мове выкарыстоўваецца шмат сінонімаў ("plug-in", "add-on", "extension") і гэта нікога не турбуе. Магчыма аднаго слова "дадатак" сапраўды дастаткова. І я бачу, што ўкраінская вікіпедыя таксама мае "додаток": https://uk.wikipedia.org/wiki/%D0%94%D0%BE%D0%B4%D0%B0%D1%82%D0%BE%D0%BA
Ці ёсць сэнс зрабіць прапанову выпраўлення "плагін"->"дадатак"?

Яшчэ адно сучаснае кампʼютарнае слова: "вікіпедыя" :-)
І некамп'ютарнае слова "тарашкевіца": https://bnkorpus.info/grammar.en.html#{%22lang%22:%22bel%22,%22word%22:%22%D1%82%D0%B0%D1%80%D0%B0%D1%88%D0%BA%D0%B5%D0%B2%D1%96%D1%86%D0%B0%22} (слоўнік Піскунова)

**Comment by mikalai-udodau** [comment]
Прапанову замены "плагін"->"дадатак", думаю, рабіць не варта, усё ж гэта розныя словы, нават калі адно з іх - варварызм.

Вікіпедыя - уласная назва праекта, можа, калі-небудзь прыйдзе час і такім словам трапляць у слоўнікі, але ён яшчэ не прыйшоў, баюся.

Слоўнік Піскунова на slounik.org, чамусьці мне здаецца, хаваецца пад абрэвіятурай СБМ (https://slounik.org/sbm/). Наўрад ці ў 2012 годзе выходзіла столькі слоўнікаў, каб гэта быў якісьці іншы. Там у СБМ з нейкіх прычын тарашкевіцы няма (https://slounik.org/sbm/l20/25), і гэта некалькі заблытвае, бо выглядае на тое, што пакуль што гэтае слова ёсць толькі ў граматычнай базе корпуса.

**Comment by ssvb** [comment]
> Вікіпедыя - уласная назва праекта, можа, калі-небудзь прыйдзе час і такім словам трапляць у слоўнікі, але ён яшчэ не прыйшоў, баюся.

Я дадаў гэтае слова ў [https://en.wiktionary.org/wiki/Вікіпедыя](https://en.wiktionary.org/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D0%B5%D0%B4%D1%8B%D1%8F) :-) Не папяровы слоўнік, але таксама можа быць карысным.

> Слоўнік Піскунова на slounik.org, чамусьці мне здаецца, хаваецца пад абрэвіятурай СБМ

СБМ - гэта іншы слоўнік на 150 тыс. словаў. Параўнанне гэтага слоўніка са слоўнікам Піскунова ёсць у артыкуле "Два слоўнікі і розныя думкі". Абодва выйшлі ў 2012 годзе.

**Comment by mikalai-udodau** [comment]
Пра два асобныя слоўнікі ў 2012 годзе - буду ведаць, дзякуй!
