### ISSUE TITLE
Для памылковага слова "леса" не прапануецца варыянт "лесу"

### ISSUE THREAD

**Issue by ssvb** [mikalai-udodau/spell-be#8]
Напрыклад: "Яны жылі каля леса". Плагін праверкі правапісу прапануе "села", "лема", "лес", "лесак", "лесам" але не "лесу".

**Comment by mikalai-udodau** [comment]
Гэта, бадай, самая простая праблема, і ў той жа час складаная. Простая, бо яшчэ калі пачынаў працу над слоўнікам, сутыкнуўся з ёй на прыкладзе слова "верха", і вырашыў яе тады даданнем дырэктывы
`REP а у       # верху`
Складаная - бо для выдалення гэтай дырэктывы былі прычыны, і не ўпэўнены, што з імі разабраўся.

**Comment by ssvb** [comment]
Дзякую за інфармацыю.

Дарэчы, ёсць магчымасць выкарыстаць continuous integration праз github actions для праверкі асэнсаванасці прапаноў. Напрыклад, для мовы праграмавання Ruby ёсць пакет [Hunspell](https://github.com/segabor/Hunspell) (`gem install hunspell`) і яго вельмі лёгка можна выкарыстаць так:

```Ruby
require 'Hunspell'
dict = Hunspell.new('dictionaries/be_BY.aff', 'dictionaries/be_BY.dic')

abort 'няма "кароў" сярод пяці першых прапаноў' unless dict.suggest('кароваў').take(5).include?('кароў')
abort 'няма "князёў" сярод пяці першых прапаноў' unless dict.suggest('князей').take(5).include?('князёў')

puts 'ніякіх праблем з якасцю прапаноў не знойдзена'
```

Такая праверка будзе аўтаматычна запускацца пасля кожнага каміту ў github. І будзе лёгка бачыць, калі нешта неспадзявана зламалася ў прапановах. Калі гэта цікава, то я магу зрабіць pull request. Замест Ruby можна выкарыстаць Python або нешта іншае.

**Comment by ssvb** [comment]
> для выдалення гэтай дырэктывы былі прычыны, і не ўпэўнены, што з імі разабраўся

Continuous integration тут якраз вельмі дапамагае. Кожны pull request будзе правераны. І калі `REP а у # верху` выклікае праблемы з іншымі прапановамі, то такі pull request будзе аўтаматычна забракаваны. Гэта вельмі зручна.

**Comment by mikalai-udodau** [comment]
Праблема там была крыху іншага плану, не ведаю, як патлумачыць. Дадаў прапанову "лесу". Што да continuous integration, на жаль, не валодаю ні рубі, ні пайтанам, і не ўпэўнены, што мне будзе цікава разбірацца ды падтрымліваць код для github actions. Так-та ўсё правільна, аўтаматычныя праверкі лепей за ручныя, але часу не хапае ні на што, на жаль. Дзякуй за прапанову.

**Comment by ssvb** [comment]
Я [тут](https://spylls.readthedocs.io/en/latest/hunspell/data_aff.html#spylls.hunspell.data.aff.RepPattern) знайшоў інфармацыю аб тым, што дырэктыва REP падтрымлівае regular expressions.
Замена літары "а" толькі пры ўмове, што яна ў слове апошняя: `REP а$ у`

**Comment by mikalai-udodau** [comment]
Акурат з гэтым і правазіўся ўчора больш за гадзіну. Пішуць, што падтрымліваецца, а насамрэч робіцца нешта зусім не тое, што трэба - прынамсі, у файрфоксе. Таму пакуль так.
